development:
  adapter: postgresql
  encoding: unicode
  database: sample_app_db
  pool: 5
  username: nikitos
  password: 197524
  port: 10000
test:
  adapter: postgresql
  encoding: unicode
  database: sample_app_db_test
  pool: 5
  username: nikitos
  password: 197524
  port: 10000
production:
  adapter: postgresql
  encoding: unicode
  database: sample_app_db_test
  pool: 5
  username: nikitos
  password: 197524
  port: 10000