development:
  adapter: postgresql
  encoding: unicode
  database: toy_app
  pool: 5
  username: nikitos
  password: 197524
test:
  adapter: postgresql
  encoding: unicode
  database: toy_apptest
  pool: 5
  username: nikitos
  password: 197524